framework:
    cache:
        app: cache.adapter.redis
        default_redis_provider: 'redis://redis:6379/0'
        pools:
            currency_rates:
                adapter: cache.adapter.redis
                provider: 'redis://redis:6379/1'
                default_lifetime: 30
