monolog:
    channels: ['security', 'performance', 'api']
    handlers:
        security:
            type: stream
            path: '%kernel.logs_dir%/security.log'
            level: warning
            channels: ['security']
        performance:
            type: stream  
            path: '%kernel.logs_dir%/performance.log'
            level: info
            channels: ['performance']
        api:
            type: stream
            path: '%kernel.logs_dir%/api.log' 
            level: info
            channels: ['api']
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event", "!security", "!performance", "!api"]

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            nested:
                type: stream
                path: php://stderr
                level: debug
                formatter: monolog.formatter.json
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]
            deprecation:
                type: stream
                channels: [deprecation]
                path: php://stderr
                formatter: monolog.formatter.json
